language: python
python:
        - "2.7_with_system_site_packages"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgfortran3 liblapack3gf python-numpy python-scipy python-matplotlib
  - "wget -O casadi.tar.gz wget http://sourceforge.net/projects/casadi/files/CasADi/$CASADIVERSION/linux/casadi-py27-np1.9.1-v2.4.0.tar.gz/download"
  - tar -zxvf casadi.tar.gz -C casadi
  - export PYTHONPATH=$PYTHONPATH:`pwd`/casadi
  - pip install pytest-cov coveralls pypng ipython[notebook]
  - wget -O ipnbdoctest.py https://gist.githubusercontent.com/jgillis/1fd60cf60a802aab89d2/raw/d6cda04c5b1aa738a6cef90dac11594a7df2d918/ipynbdoctest.py
  
install:
    - pip install .

script:
    - py.test --cov optoy --doctest-modules optoy tests
    - python ipnbdoctest.py examples/*.ipynb
    
after_success:
  coveralls
