language: python
python:
        - "2.7"
        
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgfortran3 liblapack3gf python-numpy python-scipy python-matplotlib
  - wget https://github.com/casadi/casadi/releases/download/2.1.1/python-casadi_2.1.1-2_i386.deb
  - sudo dpkg -i python-casadi_2.1.1-2_i386.deb

install:
    - pip install .

script:  echo "123"
