language: python
python:
        - "2.7_with_system_site_packages"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgfortran3 liblapack3gf python-numpy python-scipy python-matplotlib
  - "wget -O casadi.deb http://downloads.sourceforge.net/project/casadi/CasADi/2.2.0/Ubuntu-12.04/python-casadi_2.2.0-2_amd64.deb"
  - sudo dpkg -i casadi.deb

install:
    - pip install .

script:  py.test . 
